version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slim-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public public/index.php
