version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slim-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: slim-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: slim
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: slim
      MYSQL_PASSWORD: slim
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: slim-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
